const mongoose = require("mongoose")

const PaymentsSchema = mongoose.Schema({
    indianMonthlyLink:String,
    indianBiMonthlyLink:String,
    indianYearlyLink:String,
    nonIndianMonthlyLink:String,
    nonIndianBiMonthlyLink:String,
    nonIndianYearlyLink:String,
    indianMonthlyAmount:String,
    indianBiMonthlyAmount:String,
    indianYearlyAmount:String,
    nonIndianMonthlyAmount:String,
    nonIndianBiMonthlyAmount:String,
    nonIndianYearlyAmount:String,
    starterLink:String,
    starterAmount:String,
    essentialLink:String,
    essentialAmount:String,
    basicLink:String,
    basicAmount:String,
    plusLink:String,
    plusAmount:String,
    proLink:String,
    proAmount:String,
    premiumLink:String,
    premiumAmount:String,
    deluxeLink:String,
    deluxeAmount:String,
    eliteLink:String,
    eliteAmount:String,
    ultimateLink:String,
    ultimateAmount:String,
    nonIndianStarterLink: String,
nonIndianStarterAmount: String,
nonIndianEssentialLink: String,
nonIndianEssentialAmount: String,
nonIndianBasicLink: String,
nonIndianBasicAmount: String,
nonIndianPlusLink: String,
nonIndianPlusAmount: String,
nonIndianProLink: String,
nonIndianProAmount: String,
nonIndianPremiumLink: String,
nonIndianPremiumAmount: String,
nonIndianDeluxeLink: String,
nonIndianDeluxeAmount: String,
nonIndianEliteLink: String,
nonIndianEliteAmount: String,
nonIndianUltimateLink: String,
nonIndianUltimateAmount: String,
},{ timestamps: true })


module.exports = mongoose.model("Payments", PaymentsSchema)